language: node_js
node_js:
  - "10"
script:
  - npm test
after_success:
  - CI=false npm run build --project teamie-ci
  - npm install -g firebase-tools
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive