language: node_js
node_js:
  - "10"
script:
  - npm test
deploy:
  provider: firebase
  token:
    secure: "1//040bwpZ0Rhl7tCgYIARAAGAQSNwF-L9IrAKkexFRttp5eJo7MkBjqPKpctTTLCk2NwHAA2hHUtfHszP5-W4dYMMKop97T--B7Vws"